#include <mysql.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
/*DAME LOS JUGADORES QUE HAYAN MARCADO DOS O MÁS GOLES Y EL ESTADIO DONDE LO HAYAN HECHO*/

SELECT JUGADOR.USERNAME, PARTIDA.STADIO FROM (JUGADOR, PARTIDA, PUNTUACIONES) WHERE JUGADOR.ID=PUNTUACIONES.JUGADOR_ID AND PUNTUACIONES.PARTIDA_ID=PARTIDA.ID AND PUNTUACIONES.GOLS >=2;
